### ISSUE TITLE
windows是英文版的就沒辦法存正確的中文LOG，都是??

### ISSUE THREAD

**Issue by proy27** [myunco/ServerMonitor#2]
windows是英文版的就沒辦法存正確的中文LOG，都是??

**Comment by myunco** [comment]
你用的GB2312版本吗？那是给简体中文版Windows系统用的，我在帖子里也写了。
其他系统用 UTF8版本（通用版本）

**Comment by proy27** [comment]
我是用通用版
windows server 英文版
遊戲裡面會正常顯示，但是LOG就會都是??
所以我直接翻譯成英文
大概是JAVA的BUG吧

**Comment by myunco** [comment]
这样的话就不太清楚了，有时间我装个windows server英文版试一下

**Comment by myunco** [comment]
我这里试了一下倒是没发现这个问题，系统是腾讯云的 Windows Server 2016 数据中心版 64位英文版
![winserver2016engtest](https://user-images.githubusercontent.com/26001944/125902042-86d86c48-2521-4fdb-9f0b-aa4a5093f67e.png)

**Comment by myunco** [comment]
服务端是spigot-1.16.5
Java版本是Oracle JDK16

**Comment by proy27** [comment]
請問，地區是選哪裡?
![image](https://user-images.githubusercontent.com/1089409/125916201-83375769-8922-47fe-b4dd-4d8a4aee4fdd.png)

**Comment by myunco** [comment]
刚才看了下，发现腾讯云的英文系统的Language for non-Unicode programs默认是Chinese (Simplified, China)
我修改成Chinese(Traditional, Taiwan)试了试，用记事本打开后中文是显示乱码。
不过可能因为这个系统有什么简体中文补丁，我这里日志文件的编码是GBK，用其他软件选择GBK编码查看才能正常显示中文。
不知道你那里是不是这样？

**Comment by proy27** [comment]
Windows Server 2019 Datacenter 
我的日志生成就是UTF-8了

我覺得應該是JAVA的鍋，沒有用UTF-8存文字
也許你在寫入檔案文字的時候要特別指定encode吧

**Comment by myunco** [comment]
（那可能吧，目前我没指定编码，是直接从语言文件中读取然后替换了变量写到日志文件里
